Repository canonical/global-nav, pull requests merged in 2019-03, with the labels that each got.

#92 Fix backwards compatibility
  index.html
  package-lock.json
  package.json
Labels: Review: Code +1, Review: QA +1

#93 Add Instant Page lib for just-in-time preloading
  index.html
  src/js/global-nav.js
  src/js/instant-page.js
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#99 Bump version to 2.0.5
  package.json
Labels: Review: Code +1
