Repository canonical/global-nav, pull requests merged in 2019-02, with the labels that each got.

#69 Bump version to v2.0.0
  package.json
Labels: Review: Code +1

#71 Add Prettier; Use embedded SVG for logo
  .eslintrc
  .prettierignore
  .prettierrc
  .sass-lint.yml
  README.md
  bower.json
  index.html
  package.json
  rollup.config.js
  src/js/global-nav.js
  src/js/product-details.js
  src/sass/global-nav.scss
  test/index-es6-import.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#74 Move to inline svgs to remove 12 assets.ubuntu.com calls
  src/js/global-nav.js
  src/js/product-details.js
Labels: Don't merge, Review: Code +1, Review: QA +1

#76 Bump version to 2.0.1
  package.json
Labels: Review: Code +1

#75 Add inline svg help
  README.md
Labels: Review: QA +1

#83 README - Add more detail to running the project locally
  README.md
Labels: Review: Code +1, Review: QA +1

#68 Module iife split
  .eslintrc
  package.json
  rollup.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#85 Update README to document ES6 imports
  README.md
Labels: Review: Code +1

#86 Add circleci config to test build
  .circleci/config.yml
  package.json
  src/js/global-nav.js
Labels: Review: Code +1, Review: QA +1

#88 Link example to IIFE, not index import
  index.html
Labels: Review: Code +1
